### PR TITLE
Fix error if g:no_plugin_maps is not defined

### LINKED ISSUE #3: Error: E121: Undefined variable: g:no_plugin_maps
Hi!

Your commit of today return a new error when we start Neovim or Vim:
```
$ nvim
Error detected while processing /home/julioprayer/.vim/plugged/bclose.vim/plugin/bclose.vim:
line   73:
E121: Undefined variable: g:no_plugin_maps
E15: Invalid expression: !g:no_plugin_maps
Press ENTER or type command to continue
```

Could you fixt it please ;-) ?

Thanks in advance ! :-)

### PR DESCRIPTION
**Pull request by rbgrouleff**
Remapping if g:no_plugin_maps is undefined or if it is false

Fixes #3

### CODE REVIEW

**Comment by mcchrish** [comment]
@rbgrouleff I think this should be added in README. Was bugged when my `<leader>b` mapping suddenly started to have delays.

**Comment by rbgrouleff** [comment]
@mcchrish I don't think I understand how this can result in delays. Doesn't line 73 - 75 only get executed when the plugin is loaded?

**Comment by mcchrish** [comment]
@rbgrouleff it's the delay when vim waits for another key to be pressed. Since this change appear, the `<Leader>bd` is now being mapped. Which gives the delay when pressing `<leader>b`.

**Comment by rbgrouleff** [comment]
@mcchrish Oh, now I get it. I'll add a line in the readme.

**Pull request merged**
